# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Dictator Windows installer build."""

import sys
from pathlib import Path

block_cipher = None
project_root = Path(SPECPATH).parent

a = Analysis(
    [str(project_root / "dictator" / "__main__.py")],
    pathex=[str(project_root)],
    binaries=[],
    datas=[],
    hiddenimports=[
        "dictator",
        "dictator.core",
        "dictator.core.events",
        "dictator.core.states",
        "dictator.core.models",
        "dictator.core.config",
        "dictator.core.transcription",
        "dictator.core.resilience",
        "dictator.core.lifecycle",
        "dictator.core.logging",
        "dictator.platform",
        "dictator.platform.interfaces",
        "dictator.platform.factory",
        "dictator.platform.windows",
        "dictator.platform.null",
        "dictator.platform.safety",
        "dictator.agent",
        "dictator.agent.commands",
        "dictator.agent.sandbox",
        "dictator.agent.service",
        "dictator.agent.tools",
        "dictator.agent.tools.browser",
        "dictator.agent.tools.volume",
        "dictator.agent.tools.app_launcher",
        "dictator.agent.tools.keys",
        "dictator.agent.tools.reactor",
        "dictator.audio",
        "dictator.audio.stream",
        "dictator.audio.sounds",
        "dictator.ui",
        "dictator.ui.overlay",
        "dictator.ui.panels",
        "dictator.ui.tray",
        "dictator.ui.hotkeys",
        "dictator.ui.presence",
        "dictator.ui.first_run",
        "dictator.utils",
        "dictator.utils.paths",
        "dictator.utils.text",
        "dictator.app",
        # Third-party hidden imports
        "pynput.keyboard._win32",
        "pynput.mouse._win32",
        "comtypes",
        "comtypes.stream",
        "pycaw",
        "pycaw.pycaw",
        "winotify",
        "pystray",
        "pystray._win32",
        "PIL",
        "PIL.Image",
        "PIL.ImageDraw",
        "faster_whisper",
        "ctranslate2",
        "openwakeword",
        "onnxruntime",
        "sounddevice",
        "scipy.signal",
        "webrtcvad",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "matplotlib",
        "tkinter.test",
        "unittest",
        "pytest",
        "setuptools",
        "pip",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Dictator",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,  # No console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(project_root / "installer" / "icon.ico") if (project_root / "installer" / "icon.ico").exists() else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="Dictator",
)
